export const DEPLOYED_COMMERCE_STATUS = {
    mode: "live",
    shopifyConfigured: true,
    webshippyConfigured: true,
    webshippyOrderOwner: "shopify-connector",
    liveWritesEnabled: true,
    storefrontCatalog: "shopify-ucp",
    storefrontInventory: "webshippy-stock+shopify-availability",
    storefrontCheckout: "shopify-ucp",
    storefrontProducts: 3,
    storefrontCatalogCache: "cloudflare-workers-10s",
    storefrontProviderRetry: "bounded-transient-retry",
    webshippyConnection: "shopify-connector",
    webshippyTestBridge: "shopify-orders-paid-webhook",
    webshippyCancellationBridge: "shopify-orders-cancelled-webhook",
    webshippyIdempotency: "reference-reconciliation",
} as const;
